[package]
name = "downloader"
version = "1.2.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
